dependencies:
  - build.sbt
  - project/*.scala

workflow:
  - "workflow/*.py"
  - "workflow/**/*.py"

configuration:
  - src/**/*.conf
  - "*.conf"
  - ".gitignore"

project-management:
  - ".github/*"
  - "*.md"