version: 3

services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_DB: dataeng
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
  minio:
    container_name: minio
    image: minio/minio:latest
  airflow:
    container_name: airflow
    image: apache/airflow:2.0.0-python3.8